# Generated by Django 4.0.4 on 2022-07-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnTradingSwiftly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
