# Generated by Django 4.0.4 on 2022-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnTradingSwiftly', '0003_alter_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='isAdvanced',
            field=models.BooleanField(default=False),
        ),
    ]
